version: '3'

services:
  server:
    container_name: server
    restart: always 
    build: .
    ports:
      - "8080:8080"
    links: 
      - database
    volumes:
      - .:/usr/src/app
  database:
    container_name: mongodatabase
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=@Alzadialu.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
